# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisSuperUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1679, 945)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(160, -30, 1911, 1071))
        self.background.setStyleSheet("background-color:black;")
        self.background.setObjectName("background")
        self.border1 = QtWidgets.QLabel(Form)
        self.border1.setGeometry(QtCore.QRect(-10, 0, 1691, 31))
        self.border1.setText("")
        self.border1.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/gggf.jpg"))
        self.border1.setScaledContents(True)
        self.border1.setObjectName("border1")
        self.border2 = QtWidgets.QLabel(Form)
        self.border2.setGeometry(QtCore.QRect(-10, 920, 1691, 31))
        self.border2.setText("")
        self.border2.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/gggf.jpg"))
        self.border2.setScaledContents(True)
        self.border2.setObjectName("border2")
        self.jarvisborder = QtWidgets.QLabel(Form)
        self.jarvisborder.setGeometry(QtCore.QRect(10, 40, 531, 881))
        self.jarvisborder.setText("")
        self.jarvisborder.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/gggf.jpg"))
        self.jarvisborder.setScaledContents(True)
        self.jarvisborder.setObjectName("jarvisborder")
        self.jarvisui = QtWidgets.QLabel(Form)
        self.jarvisui.setGeometry(QtCore.QRect(30, 160, 491, 651))
        self.jarvisui.setText("")
        self.jarvisui.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/jarviss.gif"))
        self.jarvisui.setScaledContents(True)
        self.jarvisui.setObjectName("jarvisui")
        self.iornman = QtWidgets.QLabel(Form)
        self.iornman.setGeometry(QtCore.QRect(1290, 280, 351, 551))
        self.iornman.setText("")
        self.iornman.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/Private.gif"))
        self.iornman.setScaledContents(True)
        self.iornman.setObjectName("iornman")
        self.startpic = QtWidgets.QLabel(Form)
        self.startpic.setGeometry(QtCore.QRect(1260, 820, 211, 101))
        self.startpic.setText("")
        self.startpic.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/Start.png"))
        self.startpic.setScaledContents(True)
        self.startpic.setObjectName("startpic")
        self.quitpic = QtWidgets.QLabel(Form)
        self.quitpic.setGeometry(QtCore.QRect(1470, 830, 201, 81))
        self.quitpic.setText("")
        self.quitpic.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/Quit.png"))
        self.quitpic.setScaledContents(True)
        self.quitpic.setObjectName("quitpic")
        self.speakergif = QtWidgets.QLabel(Form)
        self.speakergif.setGeometry(QtCore.QRect(560, 290, 571, 381))
        self.speakergif.setText("")
        self.speakergif.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/Jarvis_Gui (1).gif"))
        self.speakergif.setScaledContents(True)
        self.speakergif.setObjectName("speakergif")
        self.datebox = QtWidgets.QLabel(Form)
        self.datebox.setGeometry(QtCore.QRect(520, 670, 271, 101))
        self.datebox.setText("")
        self.datebox.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/gggf.jpg"))
        self.datebox.setScaledContents(True)
        self.datebox.setObjectName("datebox")
        self.timebox = QtWidgets.QLabel(Form)
        self.timebox.setGeometry(QtCore.QRect(520, 790, 261, 111))
        self.timebox.setText("")
        self.timebox.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/gggf.jpg"))
        self.timebox.setScaledContents(True)
        self.timebox.setObjectName("timebox")
        self.initiating = QtWidgets.QLabel(Form)
        self.initiating.setGeometry(QtCore.QRect(540, 30, 441, 191))
        self.initiating.setText("")
        self.initiating.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/initial.gif"))
        self.initiating.setScaledContents(True)
        self.initiating.setObjectName("initiating")
        self.earth = QtWidgets.QLabel(Form)
        self.earth.setGeometry(QtCore.QRect(1140, 60, 261, 211))
        self.earth.setText("")
        self.earth.setPixmap(QtGui.QPixmap("../../Downloads/Jarvis UI Files-20220406T122401Z-001/Jarvis UI Files/GUI files/Earth.gif"))
        self.earth.setScaledContents(True)
        self.earth.setObjectName("earth")
        self.datetextBrowser = QtWidgets.QTextBrowser(Form)
        self.datetextBrowser.setGeometry(QtCore.QRect(540, 700, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.datetextBrowser.setFont(font)
        self.datetextBrowser.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:white;\n"
"border-radius:none;")
        self.datetextBrowser.setObjectName("datetextBrowser")
        self.timetextBrowser = QtWidgets.QTextBrowser(Form)
        self.timetextBrowser.setGeometry(QtCore.QRect(540, 820, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.timetextBrowser.setFont(font)
        self.timetextBrowser.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:white;\n"
"border-radius:none;")
        self.timetextBrowser.setObjectName("timetextBrowser")
        self.startpushButton = QtWidgets.QPushButton(Form)
        self.startpushButton.setGeometry(QtCore.QRect(1270, 840, 191, 61))
        self.startpushButton.setStyleSheet("background-color:transparent;")
        self.startpushButton.setText("")
        self.startpushButton.setObjectName("startpushButton")
        self.quitpushButton = QtWidgets.QPushButton(Form)
        self.quitpushButton.setGeometry(QtCore.QRect(1470, 840, 191, 61))
        self.quitpushButton.setStyleSheet("background-color:transparent;")
        self.quitpushButton.setText("")
        self.quitpushButton.setObjectName("quitpushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.background.setText(_translate("Form", "TextLabel"))
        self.datetextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Date: 0000-00-00</p></body></html>"))
        self.timetextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Time: 00:00:00</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
